services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "85:80"
        volumes:
            - ./:/app
        depends_on:
            - app
        tty: true
        restart: unless-stopped

    app:
        build:
            context: docker/app
        volumes:
            - ./:/app
        restart: unless-stopped
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
